### ISSUE TITLE
FIPS204 Full Standard Released

### ISSUE THREAD

**Issue by DiscordJim** [integritychain/fips204#3]
Since the full standard is out https://csrc.nist.gov/pubs/fips/204/final, will this repository be updated to address that?

Or is the current version on GitHub the latest with the full release?

**Comment by integritychain** [comment]
Hi @DiscordJim - I am in the process up updating it right now. The latest (non-published) GitHub code is passing the NIST test vectors, but I would like to do some further clean up before publishing the crate. It shouldn't be long at all ; )

**Comment by DiscordJim** [comment]
Thank you so much. Great work by the way. Also-- what is "integrity chain"?

**Comment by integritychain** [comment]
The code has been updated to match the final/released version of the spec and published as v0.4.0. Let me know if you spot any issues. (btw, IntegrityChain is just a placeholder at the moment)

**Comment by DiscordJim** [comment]
I see, what is it though? An organization?
