### ISSUE TITLE
Expose a method to get the public key from the private key

### ISSUE THREAD

**Issue by codespree** [integritychain/fips204#5]
Hi,

Thanks for your work on this library. I am using it in my [library](https://github.com/codespree/quantcrypt)

It would be very helpful if you could expose a method to get the public key given a private key.

Thanks!

**Comment by integritychain** [comment]
Hmmm, this seems doable and relatively straightforward ... let me consider a bit further before putting on my TODO short list.

**Comment by integritychain** [comment]
Implemented on Signing trait for PrivateKey in v0.4.2
