### ISSUE TITLE
Support deterministic signatures

### ISSUE THREAD

**Issue by swenson** [integritychain/fips204#8]
I noticed there is a comment in the code that a deterministic signature can be generated by setting the `rnd` to the zero array, but in the current code paths, it is always seeded from an RNG.

A user could get around this by supplying a broken RNG that [always returns 0](https://xkcd.com/221/), but it would be better if we had a method to call to get the deterministic signature (or making the RNG an `Option`, maybe?).

**Comment by integritychain** [comment]
Yes, I think you have a good point here. Let me do a little homework on the right options; I agree a separate method is likely best. I should have some time over the holidays to get this resolved.

**Comment by integritychain** [comment]
Version 0.4.6 has been published with new `...seed()` functions to support deterministic signatures. thanks for catching this!

**Comment by swenson** [comment]
Thanks!
